apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: api
    count: 1
  - name: web
    count: 1
  - name: worker-pdf
    count: 1
  - name: worker-ai
    count: 1
