services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cvstudio
      POSTGRES_PASSWORD: cvstudio
      POSTGRES_DB: cvstudio
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ['postgres', '-c', 'shared_preload_libraries=pg_stat_statements']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cvstudio']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025'
      - '1025:1025'

  api:
    profiles: ['app']
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://cvstudio:cvstudio@postgres:5432/cvstudio?schema=public
      REDIS_URL: redis://redis:6379
      PORT: '3001'
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    profiles: ['app']
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  pgdata:
