import { cvMentions } from './cv-facts';

/** Display name of each skill the heuristics can recognise. */
export const SKILL_LEXICON = [
  // Engineering
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'Kotlin',
  'Swift',
  'Go',
  'Rust',
  'C#',
  'C++',
  'PHP',
  'Ruby',
  'SQL',
  'NoSQL',
  'GraphQL',
  'REST',
  'React',
  'Next.js',
  'Vue',
  'Angular',
  'Node.js',
  'NestJS',
  'Express',
  'Django',
  'Flask',
  'Spring',
  'Laravel',
  'React Native',
  'Flutter',
  'HTML',
  'CSS',
  'Tailwind',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Kafka',
  'Docker',
  'Kubernetes',
  'Terraform',
  'AWS',
  'Azure',
  'GCP',
  'Linux',
  'Git',
  'CI/CD',
  'Microservices',
  'Testing',
  'Jest',
  'Playwright',
  'Cypress',
  'Security',
  'Accessibility',
  // Data
  'Pandas',
  'NumPy',
  'Spark',
  'Airflow',
  'dbt',
  'Tableau',
  'Power BI',
  'Excel',
  'Looker',
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Statistics',
  'ETL',
  'Data Analysis',
  'Data Visualization',
  // Product, design, business
  'Figma',
  'Sketch',
  'UX Research',
  'Prototyping',
  'Design Systems',
  'User Testing',
  'Product Management',
  'Roadmapping',
  'Agile',
  'Scrum',
  'Kanban',
  'Jira',
  'A/B Testing',
  'SEO',
  'SEM',
  'Google Analytics',
  'Content Marketing',
  'Copywriting',
  'Social Media',
  'CRM',
  'Salesforce',
  'HubSpot',
  'Negotiation',
  'Budgeting',
  'Forecasting',
  'Recruiting',
  'Customer Success',
  'Project Management',
  'Stakeholder Management',
  // Transferable
  'Leadership',
  'Mentoring',
  'Public Speaking',
  'Team Management',
  'Communication',
];

/** Lexicon skills a text mentions, in lexicon order (any case: for job descriptions). */
export function skillsIn(text: string): string[] {
  const lower = text.toLowerCase();
  return SKILL_LEXICON.filter((skill) => cvMentions(lower, skill.toLowerCase()));
}

/** True when a keyword is a known skill name. */
export function isKnownSkill(keyword: string): boolean {
  const key = keyword.toLowerCase();
  return SKILL_LEXICON.some((skill) => skill.toLowerCase() === key);
}
